[package]
name = "mango-chat-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.0"
actix-web = "4"
actix-web-actors = "4.1.0"
serde_json = "1.0.85"
serde = { version = "1.0.145", features = ["derive"] }
env_logger = "0.9.1"
rand = "0.8.5"
simplelog = "0.12.0"
log = "0.4.17"
